version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: golang_database
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"

    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d/init.sql
    networks:
      - golang_api_network

volumes:
  mysql_data:

networks:
  golang_api_network:
    driver: bridge
