version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-restapi
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: golang_database
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - golang_api_network

volumes:
  mysql_data:

networks:
  golang_api_network:
    driver: bridge
